{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "draupnir.fullname" . }}-pvc
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  {{- with .Values.persistence.resources }}
  resources:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
