kind: Secret
apiVersion: v1
metadata:
  name: {{ include "draupnir.fullname" . }}-config-secret
  labels:
    {{- include "draupnir.labels" . | nindent 4 }}
data:
    config.yaml: {{ .Values.config | b64enc | quote }}
