kind: Secret
apiVersion: v1
metadata:
  name: {{ include "draupnir.fullname" . }}-config-secret
  labels:
    {{- include "draupnir.labels" . | nindent 4 }}
stringData:
    config.yaml: |
      {{ .Values.config | toYaml | nindent 6 }}
