{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "draupnir.fullname" . }}
  labels:
    {{- include "draupnir.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "draupnir.selectorLabels" . | nindent 4 }}
{{- end }}